name: Renewal Cache

on:
  schedule:
    - cron: "*/5 * * * *"
  
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Get API Token
      id: token
      run: |
        python login_session.py >> $GITHUB_OUTPUT

    - name: Renewal Cache
      run: |
        curl \
        -X POST https://nbr4i2hehe.execute-api.ap-northeast-2.amazonaws.com/test/cache \
        -d '{"token": "${{ steps.token.outputs.login-token }}"}'